### ISSUE TITLE
Import clash

### ISSUE THREAD

**Issue by noapocalypse** [TheCloudScout/sentinel-pricing#13]
![image](https://user-images.githubusercontent.com/6807001/204322210-6d76a213-1e39-482f-be63-3f6a33eed4ff.png)

Hi, do you have a way to workaround this in the script?

**Comment by TheCloudScout** [comment]
Hi there!

Ok, a couple of things to try here:

1. Managing multiple PowerShell module version can be quite a challenge. Firstly, I think the easiest solution is to update the current modules so that the latest version is download and loaded. <br><br>Just run: `Update-Module Az`

2. Another thing I noticed is that my scripts checks for installed modules but uses the `-All` switch so that both Windows PowerShell and PowerShell Core modules might be listed. It might have caused the script to skip the step of installing the appropriate version. So please first pull the latest version and try again. 

4. You could also track down the older versions and remove them manually:
```
Get-Module -ListAvailable -Name "Az.Accounts"

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.10.3                Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     2.8.0                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
```
<sub>_In this example, I'd like to keep 2.10.3 (latest) and remove 2.8.0_</sub>

`Get-Module -ListAvailable -Name "Az.Accounts" | Where-Object { $_.Version -ne "2.10.3" } | Uninstall-Module`

<br>
Please let me know if any of these steps were useful!

**Comment by noapocalypse** [comment]
Good call, will give this a bash today Cheers

**Comment by noapocalypse** [comment]
That fixed it :)  cheers.

As an aside, I'd love to see a simple version of this that could be ran from a Sentinel notebook. So one that outputs the table only no updates. Wo8uld be great for a customer to be able to check their spending by opening a notebook and pressing a button then there it is in a report kind of thing. Apologies I know this isn't the best place to suggest this :D

**Comment by noapocalypse** [comment]
Addition: Interestingly running the script from Azure PowerShell causes a conflict every time after the initial run.
I got around this by removing the install commands and adding remove as a command everytime

  `
Remove-Module -FullyQualifiedName @{ModuleName = "Az.Accounts"; ModuleVersion = "2.9.1"}
Import-Module -Name Az.Accounts -MinimumVersion 2.10.0
`

**Comment by TheCloudScout** [comment]
> As an aside, I'd love to see a simple version of this that could be ran from a Sentinel notebook. So one that outputs the table only no updates. Would be great for a customer to be able to check their spending by opening a notebook and pressing a button then there it is in a report kind of thing. Apologies I know this isn't the best place to suggest this :D

Well if you provide a subscriptionId it will only check for workspaces there. I can incorporate an additional parameter for specifying a specific single workspace as well. Would that solve your needs?

The default parameter `updateArmParameters` is already on `$false` by default. So it shouldn't bother with changing ARM template files at all while ran without this.

```
./powershell-script/AzSentinelPricingOptimizer.ps1 `
    -subscriptionId '< YOUR SUBSCRIPTION ID >' `
```

Let me know if specifying a single workspace is important to you.

**Comment by noapocalypse** [comment]
I ended up butchering the script a bit :) 

Basically stripped out some bits i didn't need and ran this in an Azure Powershell Terminal -- after running the original script with a subscription ID i kept hitting failures on subsequent runs -- this does what i need :) Thanks

The aside around the Sentinel notebook was just more of the thought of being able to put it in an environment for a one click check sort of thing but running this manually once a month is fine :) To simplify running it, no PowerShell knowledge and no git repo etc. needed just a button or task :)

I didn't need the ARM updating as they are all sorts of convoluted at the mo :D

It's a great script thanks very much for sharing
