### ISSUE TITLE
question regarding the Excel sheet 

### ISSUE THREAD

**Issue by mezzofix** [TheCloudScout/sentinel-pricing#14]
hi,

can't get your Excel to work tbh. Not sure what I'm doing wrrong but have added the rates as of today West Europe region as seen here https://azure.microsoft.com/en-us/pricing/details/monitor/ 
![image](https://github.com/TheCloudScout/sentinel-pricing/assets/57439630/7d2ee2cc-b648-4a53-88c8-27c9d972acf2)

![image](https://github.com/TheCloudScout/sentinel-pricing/assets/57439630/c0d2724d-f80a-42f5-b728-3b41780c7e0b)

Per my calculation if I'm on 100GB/day where I pay a daily rate of 228,95 Euro and everything above is charged €2.29 per GB in the 100GB/ commitment tier it would already make sense to upgrade to the 200GB/day tier when ingesting 180GB daily in the 100GB/d tier:

228,96 €(100GB/daily) + 85GB x €2.29 per GB (for any GB above the 100GB limit in the tier) not above 193 GB as stated in the sheet. 

100GB/daily = 228,96 €  + 85GB x €2.29 per GB = 423 € 

Or am I wrrong ?

**Comment by EEN421** [comment]
Hey Mezzofix,

you’re totally right. I didn’t write this so I don’t have an answer for you (yet). I have recently forked this repo from https://github.com/TheCloudScout/sentinel-pricing and haven’t changed anything.

I’m planning on repurposing it for use in the US as part of a cost optimization exercise I’m working on. I’m out of office next week to speak about cost optimization at the BlueVoyant company summit in DC, but expect to start working on this in early June.  I’d be more than happy to share my results with you when I start working on this repo too. Sorry I can’t be of more help at this time.

Thanks for checking out my GitHub page! If you’re interested in Sentinel Cost Optimization, check out my KQL query repo https://github.com/EEN421/KQL-Queriesblog and Sentinel Cost Optimization blog at www.DevSecOpsDad.com<http://www.DevSecOpsDad.com> which contains step-by-step guides and exercises that I’m constantly updating.

Have a great rest of your day and don’t hesitate to reach out if there’s anything else I can help out with.

Cheers,
Ian

**Comment by TheCloudScout** [comment]
Hi @mezzofix and @EEN421! Thanks for reaching out to me. Let me see if I can help you out here...

> can't get your Excel to work tbh. Not sure what I'm doing wrrong but have added the rates as of today West Europe region as seen here https://azure.microsoft.com/en-us/pricing/details/monitor/ ![image](https://user-

The URL you provide points toward the Log Analytics (Azure Monitor) pricing only. Sentinel costs promrise of two parts:
1. Sentinel ingest costs
2. Azure Monitor / Log Analytics ingest cost for the underlying storage technology.

This means you have to update both of the columns with their respective prices.

But to be honest, if you're paying standard list prices, the thresholds will be the same.
Microsoft recently increased some prices which I adjusted in the Excel sheet a second ago. Since everything went up with the same percentage, the threshold remain the same. Even after using the Dollar prices for Central US, the differences is only a couple of GBs at best.

Check this example:

<img width="1469" alt="image" src="https://github.com/TheCloudScout/sentinel-pricing/assets/29123012/aef4a3dd-ed56-40f4-8452-dfb3695a82c5">

I think you probably will only benefit for calculating your own thresholds, if you're have an Enterprise Agreement with variable discounts en special prices you negotiated with Microsoft.

But also don't forget to alter the thresholds in the PowerShell script afterwards as shown in the screenshot above.

> Per my calculation if I'm on 100GB/day where I pay a daily rate of 228,95 Euro and everything above is charged €2.29 per GB in the 100GB/ commitment tier it would already make sense to upgrade to the 200GB/day tier when ingesting 180GB daily in the 100GB/d tier:
> 
> 228,96 €(100GB/daily) + 85GB x €2.29 per GB (for any GB above the 100GB limit in the tier) not above 193 GB as stated in the sheet.
> 
> 100GB/daily = 228,96 € + 85GB x €2.29 per GB = 423 €
> 
> Or am I wrrong ?

You are using 180GB and 185GB in the same calculation. But the exact **threshold** currently lies at 188GB a day.
Both 180GB and 185GB (your calculations) are better of with a 100GB/day tier. Since the total amount if less than what a 200GB/day commitment tier will cost you at € 429,87

But first of all, I DID update the Excel sheet. Perhaps the threshold has changed because of this, or maybe I made a mistake in the past. The exact threshold for going to 200GB/day commitment currently is 188GB. This means that if you're ingesting between 85GB (previous threshold) and 188GB a day, your best choice is to go for a 100GB/day commitment tier. **These values act as thresholds before going for the next tier!**
(This is for Log Analytics! For Sentinel the thresholds are 50GB and 180GB respectively)

The important point I wanted to make here that if you do not need to reach exactly 200GB/day or more before a higher commitment tier becomes most optimal. If you ingest 189 GB/day and keep your commitment tier at 100GB the calculation with look like this:

100GB/day commitment tier = € 228,95 a day
89GB overage/day = € 2,29 x 89 = € 203,81
Together: € 432,76

That means that you would've been better of with a 200GB/day pricing tier since that one costs € 429,87, which is less.

Especially with the Sentinel tiers the thresholds can be lower because the discounts are also higher. If you're ingesting more than 50GB/day, it already makes sense to go for a 100GB/day commitment tier. The discount is that large, that you'll pay less.

And you can mix and match!
* if you ingest 70GB/day, keep your Log Analytics at pay-per-GB and set Sentinel at 100GB/day.
* if you ingest 1900GB/day, keep your Log Analytics at 1000GB/day and set Sentinel at 2000GB/day.

I hope this is clarified. If you have any other questions pleach reach out to me again.

Make sure to pull the latest updates I've just committed.

@EEN421 if you happen to come up with some other improvements I would be very pleased if you take the effort to initiate a pull request to improve the code on my side as well so me and other can benefit from your improvements as well. 👌🏻😊
